(FACT-2477) Add dependency on lsb-release
Puppet 6 bundles Facter 3 which needs lsb-release to gather some facts
required by puppetlabs modules apt and postgresql.

When the package is not installed, these modules raise the most cryptic
error for new users:

```
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /etc/puppetlabs/code/environments/production/modules/apt/manifests/source.pp, line: 102, column: 9) (file: /etc/puppetlabs/code/modules/syslog_ng/manifests/repo.pp, line: 22) on node ubuntu1804-64.example.com
```