(maint) Update Alpine Docker container to 3.11
- Requires pinning cmake back to 3.10 repo, as the 3.11 version of cmake
  crashes if it doesn't have libstdc++-9.2.0-r4, and gcc 6 / g++ 6
  require the older libstdc++ 6 series

- Similarly, pin back boost-dev=1.69.0-r4 yaml-cpp-dev=0.6.2-r2 for the
  same reason as the linking process will fail with errors like:

 #11 175.7 /usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libboost_locale.so.1.71.0: undefined reference to `std::__cxx11::basic_ostringstream<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_ostringstream()'
 #11 175.7 /usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libboost_locale.so.1.71.0: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
 #11 175.7 /usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libboost_locale.so.1.71.0: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
 #11 175.7 collect2: error: ld returned 1 exit status

 #29 467.9 /usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../lib/libyaml-cpp.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'

  These both require the newer libstdc++ for ABI compat, but we're
  forced to use the older libstdc++ due to required compiler toolchain.

- In the runtime container, also pull binary packages from the 3.10
  repository for the relevant boost libraries and yaml-cpp. Boost is
  from main, while yaml-cpp is from community. Add boost-locale package
  and explicitly reference boost-log package as well, which was
  previously included as a transitive dependency. Remove the "boost"
  package to prevent it from dragging in unnecessary dependencies like
  boost-python2 and boost-python3 (that depend on python2 and python3)
  which inflate the container size by 80MB+

- Upgrades Ruby to 2.6.6p146, which requires a change from --no-ri
  --no-rdoc to --no-document when installing gems.

- Remove the --update-cache flag from apk add for the gcc / g++ 6
  compilers b/c --no-cache is in use to prevent needing removals of
  the apk cache on final image.