Pin sqlite3 rubygem to 1.6.9
The test started failing on RHEL8 ARM with:

    $ env GEM_HOME=/opt/puppetlabs/puppet/lib/ruby/vendor_gems env PATH="/opt/puppetlabs/puppet/bin:${PATH}" gem install sqlite3 -v 1.7.0 -- --enable-system-libraries
      ERROR:  Error installing sqlite3:
      	The last version of sqlite3 (= 1.7.0) to support your Ruby & RubyGems was 1.7.0. Try installing it with `gem install sqlite3 -v 1.7.0` and then running the current command again
      	sqlite3 requires Ruby version >= 3.0, < 3.4.dev. The current ruby version is 2.7.8.225.

The sqlite3 gem dropped "native gem support for 2.7" in 1.7.0. So pin to the
version just prior to that.