(RE-5985) Cleanup package dependencies for Cisco wrlinux
puppet-agent rpm for Cisco wrlinux would throw dependency issues when installed via rpm.

```
root@t2txsshdfijcslg:~# rpm -i puppet-agent-1.2.7.385.g8450f42-1.cisco_wrlinux7.x86_64.rpm
error: Failed dependencies:
	/etc/profile.d is needed by puppet-agent-1.2.7.385.g8450f42-1.cisco_wrlinux7.x86_64
	/usr/doc is needed by puppet-agent-1.2.7.385.g8450f42-1.cisco_wrlinux7.x86_64
```

This is due to /etc/profile.d being owned by non-standard packages and /usr/doc is non-existent on the platform.

This commit sets the Cisco specific packages as a dependency to eliminate the /etc/profile.d warning and moves the BOM into the puppet namespace.

```
bash-4.2$ rpm -qi platform
Name        : platform                     Relocations: (not relocatable)
Version     : 1.0.0                             Vendor: (none)
Release     : r0                            Build Date: Thu 03 Sep 2015 11:34:34 PM UTC
Install Date: Fri 04 Sep 2015 12:24:20 AM   Build Host: ins-sw-bld57
Group       : utilities                     Source RPM: platform-1.0.0-r0.src.rpm
Size        : 17565245                         License: Proprietary
Signature   : DSA/SHA1, Thu 03 Sep 2015 11:34:34 PM UTC, Key ID b8484f9bae501f80
Packager    : Cisco Systems <info@cisco.com>
URL         : http://cisco.com/
Summary     : Cisco N9000 platform init package
Architecture: lib32_n9000
Description :
The set of Cisco (proprietary) packages for plaform initialization
```

```
[vm_node0_RP0_CPU0:~]$ rpm -qi cisco-config
Name        : cisco-config                 Relocations: (not relocatable)
Version     : 0.1                               Vendor: (none)
Release     : r0.0                          Build Date: Thu Oct  8 05:40:26 2015
Install Date: Thu Oct  8 06:43:10 2015      Build Host: sjc-ads-6761
Group       : base                          Source RPM: cisco-config-0.1-r0.0.src.rpm
Size        : 3101                             License: CLOSED
Signature   : DSA/SHA1, Thu Oct  8 05:40:26 2015, Key ID 514a734d769e1429
Packager    : Wind River <info@windriver.com>
Summary     : Cisco system configurations
Architecture: x86_64
Description :
Cisco system configurations.
```